// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tunnel

import (
	"github.com/go-gost/gost.plus/config"
	"github.com/go-gost/x/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTunnel creates a new instance of MockTunnel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTunnel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTunnel {
	mock := &MockTunnel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTunnel is an autogenerated mock type for the Tunnel type
type MockTunnel struct {
	mock.Mock
}

type MockTunnel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTunnel) EXPECT() *MockTunnel_Expecter {
	return &MockTunnel_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockTunnel
func (_mock *MockTunnel) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnel_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockTunnel_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) Close() *MockTunnel_Close_Call {
	return &MockTunnel_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockTunnel_Close_Call) Run(run func()) *MockTunnel_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_Close_Call) Return(err error) *MockTunnel_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnel_Close_Call) RunAndReturn(run func() error) *MockTunnel_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Endpoint provides a mock function for the type MockTunnel
func (_mock *MockTunnel) Endpoint() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Endpoint")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTunnel_Endpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Endpoint'
type MockTunnel_Endpoint_Call struct {
	*mock.Call
}

// Endpoint is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) Endpoint() *MockTunnel_Endpoint_Call {
	return &MockTunnel_Endpoint_Call{Call: _e.mock.On("Endpoint")}
}

func (_c *MockTunnel_Endpoint_Call) Run(run func()) *MockTunnel_Endpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_Endpoint_Call) Return(s string) *MockTunnel_Endpoint_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTunnel_Endpoint_Call) RunAndReturn(run func() string) *MockTunnel_Endpoint_Call {
	_c.Call.Return(run)
	return _c
}

// Entrypoint provides a mock function for the type MockTunnel
func (_mock *MockTunnel) Entrypoint() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Entrypoint")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTunnel_Entrypoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Entrypoint'
type MockTunnel_Entrypoint_Call struct {
	*mock.Call
}

// Entrypoint is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) Entrypoint() *MockTunnel_Entrypoint_Call {
	return &MockTunnel_Entrypoint_Call{Call: _e.mock.On("Entrypoint")}
}

func (_c *MockTunnel_Entrypoint_Call) Run(run func()) *MockTunnel_Entrypoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_Entrypoint_Call) Return(s string) *MockTunnel_Entrypoint_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTunnel_Entrypoint_Call) RunAndReturn(run func() string) *MockTunnel_Entrypoint_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function for the type MockTunnel
func (_mock *MockTunnel) Err() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnel_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MockTunnel_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) Err() *MockTunnel_Err_Call {
	return &MockTunnel_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *MockTunnel_Err_Call) Run(run func()) *MockTunnel_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_Err_Call) Return(err error) *MockTunnel_Err_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnel_Err_Call) RunAndReturn(run func() error) *MockTunnel_Err_Call {
	_c.Call.Return(run)
	return _c
}

// Favorite provides a mock function for the type MockTunnel
func (_mock *MockTunnel) Favorite(b bool) {
	_mock.Called(b)
	return
}

// MockTunnel_Favorite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Favorite'
type MockTunnel_Favorite_Call struct {
	*mock.Call
}

// Favorite is a helper method to define mock.On call
//   - b
func (_e *MockTunnel_Expecter) Favorite(b interface{}) *MockTunnel_Favorite_Call {
	return &MockTunnel_Favorite_Call{Call: _e.mock.On("Favorite", b)}
}

func (_c *MockTunnel_Favorite_Call) Run(run func(b bool)) *MockTunnel_Favorite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *MockTunnel_Favorite_Call) Return() *MockTunnel_Favorite_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTunnel_Favorite_Call) RunAndReturn(run func(b bool)) *MockTunnel_Favorite_Call {
	_c.Run(run)
	return _c
}

// ID provides a mock function for the type MockTunnel
func (_mock *MockTunnel) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTunnel_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockTunnel_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) ID() *MockTunnel_ID_Call {
	return &MockTunnel_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockTunnel_ID_Call) Run(run func()) *MockTunnel_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_ID_Call) Return(s string) *MockTunnel_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTunnel_ID_Call) RunAndReturn(run func() string) *MockTunnel_ID_Call {
	_c.Call.Return(run)
	return _c
}

// IsClosed provides a mock function for the type MockTunnel
func (_mock *MockTunnel) IsClosed() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsClosed")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTunnel_IsClosed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsClosed'
type MockTunnel_IsClosed_Call struct {
	*mock.Call
}

// IsClosed is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) IsClosed() *MockTunnel_IsClosed_Call {
	return &MockTunnel_IsClosed_Call{Call: _e.mock.On("IsClosed")}
}

func (_c *MockTunnel_IsClosed_Call) Run(run func()) *MockTunnel_IsClosed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_IsClosed_Call) Return(b bool) *MockTunnel_IsClosed_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTunnel_IsClosed_Call) RunAndReturn(run func() bool) *MockTunnel_IsClosed_Call {
	_c.Call.Return(run)
	return _c
}

// IsFavorite provides a mock function for the type MockTunnel
func (_mock *MockTunnel) IsFavorite() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsFavorite")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockTunnel_IsFavorite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFavorite'
type MockTunnel_IsFavorite_Call struct {
	*mock.Call
}

// IsFavorite is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) IsFavorite() *MockTunnel_IsFavorite_Call {
	return &MockTunnel_IsFavorite_Call{Call: _e.mock.On("IsFavorite")}
}

func (_c *MockTunnel_IsFavorite_Call) Run(run func()) *MockTunnel_IsFavorite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_IsFavorite_Call) Return(b bool) *MockTunnel_IsFavorite_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockTunnel_IsFavorite_Call) RunAndReturn(run func() bool) *MockTunnel_IsFavorite_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockTunnel
func (_mock *MockTunnel) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTunnel_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockTunnel_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) Name() *MockTunnel_Name_Call {
	return &MockTunnel_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockTunnel_Name_Call) Run(run func()) *MockTunnel_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_Name_Call) Return(s string) *MockTunnel_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTunnel_Name_Call) RunAndReturn(run func() string) *MockTunnel_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Options provides a mock function for the type MockTunnel
func (_mock *MockTunnel) Options() Options {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Options")
	}

	var r0 Options
	if returnFunc, ok := ret.Get(0).(func() Options); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(Options)
	}
	return r0
}

// MockTunnel_Options_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Options'
type MockTunnel_Options_Call struct {
	*mock.Call
}

// Options is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) Options() *MockTunnel_Options_Call {
	return &MockTunnel_Options_Call{Call: _e.mock.On("Options")}
}

func (_c *MockTunnel_Options_Call) Run(run func()) *MockTunnel_Options_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_Options_Call) Return(options Options) *MockTunnel_Options_Call {
	_c.Call.Return(options)
	return _c
}

func (_c *MockTunnel_Options_Call) RunAndReturn(run func() Options) *MockTunnel_Options_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockTunnel
func (_mock *MockTunnel) Run() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTunnel_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockTunnel_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) Run() *MockTunnel_Run_Call {
	return &MockTunnel_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *MockTunnel_Run_Call) Run(run func()) *MockTunnel_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_Run_Call) Return(err error) *MockTunnel_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTunnel_Run_Call) RunAndReturn(run func() error) *MockTunnel_Run_Call {
	_c.Call.Return(run)
	return _c
}

// SetStats provides a mock function for the type MockTunnel
func (_mock *MockTunnel) SetStats(stats config.ServiceStats) {
	_mock.Called(stats)
	return
}

// MockTunnel_SetStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStats'
type MockTunnel_SetStats_Call struct {
	*mock.Call
}

// SetStats is a helper method to define mock.On call
//   - stats
func (_e *MockTunnel_Expecter) SetStats(stats interface{}) *MockTunnel_SetStats_Call {
	return &MockTunnel_SetStats_Call{Call: _e.mock.On("SetStats", stats)}
}

func (_c *MockTunnel_SetStats_Call) Run(run func(stats config.ServiceStats)) *MockTunnel_SetStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(config.ServiceStats))
	})
	return _c
}

func (_c *MockTunnel_SetStats_Call) Return() *MockTunnel_SetStats_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTunnel_SetStats_Call) RunAndReturn(run func(stats config.ServiceStats)) *MockTunnel_SetStats_Call {
	_c.Run(run)
	return _c
}

// Stats provides a mock function for the type MockTunnel
func (_mock *MockTunnel) Stats() config.ServiceStats {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 config.ServiceStats
	if returnFunc, ok := ret.Get(0).(func() config.ServiceStats); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(config.ServiceStats)
	}
	return r0
}

// MockTunnel_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockTunnel_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) Stats() *MockTunnel_Stats_Call {
	return &MockTunnel_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *MockTunnel_Stats_Call) Run(run func()) *MockTunnel_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_Stats_Call) Return(serviceStats config.ServiceStats) *MockTunnel_Stats_Call {
	_c.Call.Return(serviceStats)
	return _c
}

func (_c *MockTunnel_Stats_Call) RunAndReturn(run func() config.ServiceStats) *MockTunnel_Stats_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockTunnel
func (_mock *MockTunnel) Status() *service.Status {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 *service.Status
	if returnFunc, ok := ret.Get(0).(func() *service.Status); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Status)
		}
	}
	return r0
}

// MockTunnel_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockTunnel_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) Status() *MockTunnel_Status_Call {
	return &MockTunnel_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *MockTunnel_Status_Call) Run(run func()) *MockTunnel_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_Status_Call) Return(status *service.Status) *MockTunnel_Status_Call {
	_c.Call.Return(status)
	return _c
}

func (_c *MockTunnel_Status_Call) RunAndReturn(run func() *service.Status) *MockTunnel_Status_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type MockTunnel
func (_mock *MockTunnel) Type() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTunnel_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockTunnel_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockTunnel_Expecter) Type() *MockTunnel_Type_Call {
	return &MockTunnel_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockTunnel_Type_Call) Run(run func()) *MockTunnel_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTunnel_Type_Call) Return(s string) *MockTunnel_Type_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTunnel_Type_Call) RunAndReturn(run func() string) *MockTunnel_Type_Call {
	_c.Call.Return(run)
	return _c
}
